### ISSUE TITLE
Arm64 Builds for M1 Macs

### ISSUE THREAD

**Issue by Moulick** [bitnami/bitnami-docker-elasticsearch#101]
### Name and Version

bitnami/elasticsearch

### What is the problem this feature will solve?

Be able to run on M1 Macs efficiently.

### What is the feature you are proposing to solve the problem?

There are already official arm64 builds available at https://hub.docker.com/r/arm64v8/elasticsearch. Would be great to have Bitnami builds of elasticsearch for arm64.

**Comment by carrodher** [comment]
Hi, we have created this issue https://github.com/bitnami/charts/issues/7305 that is pinned in the Bitnami Helm Charts repository, on this way we can funnel all the conversation in a single place regarding ARM64 support.

We will close the rest of the existing issues just to avoid duplications, please visit the above-mentioned issue to see any new (when possible) about this topic.
