### ISSUE TITLE
Error executing 'postInstallation': Invalid kernel settings. Elasticsearch requires at least

### ISSUE THREAD

**Issue by longzhiwuing** [bitnami/bitnami-docker-elasticsearch#43]
Hi,I am using a vmware vitual machine and it seems like i should config the vm.max_map_count in the docker container .But i don't know how to config it. Please help me

when I use docker-compose.yml to install es:lastest There is a problem like belows:
```elasticsearch-node1_1  | nami    INFO  Initializing elasticsearch

elasticsearch-node1_1  | Error executing 'postInstallation': Invalid kernel settings. Elasticsearch requires at least: 

elasticsearch-node1_1  | - vm.max_map_count = 262144 

elasticsearch-node1_1  | - fs.file-max = 65536

**Comment by javsalgar** [comment]
Hi,

I think this is done by editing `/etc/sysctl.conf`. There you can add the proper values. 

Then execute

```
sudo sysctl -p
```

**Comment by longzhiwuing** [comment]
Thanks. it works for me
