### ISSUE TITLE
Pod fails to start when elasticsearch_custom.yml is mounted with read-only permissions

### ISSUE THREAD

**Issue by lightnet328** [bitnami/bitnami-docker-elasticsearch#44]
I deployed Elasticsearch to Kubernetes using Helm.
https://github.com/bitnami/charts

ConfigMap volumes have been read-only since Kubernetes 1.9.4. 
https://github.com/kubernetes/kubernetes/pull/58720

Then Pod outputs the following error and exits.

```
Welcome to the Bitnami elasticsearch container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-elasticsearch
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-elasticsearch/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing elasticsearch
Error executing 'postInstallation': EROFS: read-only file system, chown '/bitnami/elasticsearch/conf/elasticsearch_custom.yml'
```

Is there any solution to this?

**Comment by juan131** [comment]
Hi @lightnet328 

We are currently woking on fixing the ES Chart as you can check on the PR https://github.com/bitnami/charts/pull/641 

As you mentioned there were some issues such as the one you found. Sorry for the inconveniences. We will keep you updated and ping you as soon as the new ES chart is released.

**Comment by juan131** [comment]
Hi @lightnet328 

I forgot to update this issue but the ES chart was already fixed and we included several new features on it some time ago. 

Please feel free to use the new ES chart and re-open this issue if you continue facing issues with it.
