### ISSUE TITLE
Config dir listed as conf in README and config in script

### ISSUE THREAD

**Issue by aleeve** [bitnami/bitnami-docker-elasticsearch#47]
Hi! In the readme it says that custom configs should be mounted to 

`/opt/bitnami/elasticsearch/conf
`
but the scripts checks for files at 

`/opt/bitnami/elasticsearch/config
`
https://github.com/bitnami/bitnami-docker-elasticsearch/blob/dfceddefd312a9275448522aa6666fa0504473e3/6/debian-9/rootfs/libelasticsearch.sh#L16

Kind regards,
Alex

**Comment by tompizmor** [comment]
Hi @aleeve,

Thanks for reporting the issue. We did some big improvements in the Elasticsearch container recently but it seems we left some documentation issues behind. I just fixed this one https://github.com/bitnami/bitnami-docker-elasticsearch/commit/01509968c79cce2c73ebf416c466c7a200e22f56
