### ISSUE TITLE
Install elasticsearch plugin

### ISSUE THREAD

**Issue by AmirHo3ein13** [bitnami/bitnami-docker-elasticsearch#54]
**Description**

I want to install ParsiAnalyzer on elasticsearch. In local I installed it using elasticsearch-plugin with this link: `https://www.dropbox.com/s/niy3kg6ufossx6h/ParsiAnalyzer-6.4.2.zip\?dl\=1`.  
But in deployment created with bitnami chart, I can't install it.

**Comment by rafariossaa** [comment]
Hi @AmirHo3ein13 ,
  Could you indicate in which version of elasticsearch are you trying to install the plugin?
  Could you indicate if there are some errors ?

Thanks forehand
Rafael Rios

**Comment by rafariossaa** [comment]
Hi @AmirHo3ein13,
  Currently it is we need to make some changes in our elasticsearch chart to document and have an example of this feature.
  You can add to the values.yaml:
```
plugins:
  - https://www.dropbox.com/s/niy3kg6ufossx6h/ParsiAnalyzer-6.4.2.zip\?dl\=1
```

Best regards.
Rafael Rios.

**Comment by AmirHo3ein13** [comment]
@rafariossaa Thank you very much.
