### ISSUE TITLE
missing debian builds

### ISSUE THREAD

**Issue by sameersbn** [bitnami/bitnami-docker-elasticsearch#55]
**Description**

debian builds do not exist since `5.6.13-r26` release

```bash
# docker pull bitnami/elasticsearch:5.6.14-r0
Error response from daemon: manifest for bitnami/elasticsearch:5.6.14-r0 not found
```

**Describe the results you expected:**

`docker pull bitnami/elasticsearch:5.6.14-r0` should download the latest release of 5x branch

**Comment by juan131** [comment]
Hi @sameersbn 

Thanks for noticing it! There was an issue in the release process. We just released both `6.5.3-r0` and `5.6.14-r0` version of ElasticSearch. 

I proceed to close this issue. Please reopen it if you need further assistance.
