### ISSUE TITLE
discovery.zen.minimum_master_nodes is too low

### ISSUE THREAD

**Issue by javieryanez** [bitnami/bitnami-docker-elasticsearch#56]
**Description**

Despite defining the environment variable  ELASTICSEARCH_MINIMUM_MASTER_NODES = 2, the log show this warning:

`value for setting "discovery.zen.minimum_master_nodes" is too low. This can result in data loss! Please set it to at least a quorum of master-eligible nodes (current value: [-1], total number of master-eligible nodes used for publishing in this round: [2])`

I tested it with the last image of version 5 and 6 (Debian).

I see ELASTICSEARCH_MINIMUM_MASTER_NODES is not in elasticsearch-inputs.json, is that right?

**Comment by javieryanez** [comment]
This isn't right: ELASTICSEARCH_MINIMUM_MASTER_NODES = 2 

That's right (without spaces): ELASTICSEARCH_MINIMUM_MASTER_NODES=2

**Comment by javsalgar** [comment]
Hi,

So, just to confirm, the issue was with the spaces?

**Comment by javieryanez** [comment]
Hi,

Excuse me for not explaining it well. The Elasticsearch Bitnami image is working correctly.

The only problem is that I put extra spaces. I should have looked at it longer before creating an issue.

**Comment by javsalgar** [comment]
Ok! If you find any issue, don't hesitate to open a ticket :)
