### ISSUE TITLE
Improve validate_sysctl_key with 64 bit unsigned int

### ISSUE THREAD

**Issue by yanmorinokamca** [bitnami/bitnami-docker-elasticsearch#57]
When using the docker on debian linux x86_x64, the verification for kernel option fs.file-max fail because the kernel use the maximum integer possible on a 64 unsigned integer and bash use a signed integer.

**Steps to reproduce the issue:**

1. Check that /sbin/sysctl -n fs.file-max  returns 18446744073709551615
2. Use the docker for elasticsearch 6 (debian)

**Describe the results you received:**
ERROR ==> Invalid kernel settings. Elasticsearch requires at least: fs.file-max = 65536

**Describe the results you expected:**

No Error

Possibles solutions:
1. use a lower fs.file-max like 1844674407370955161  (without the 5) with: 
sysctl -w fs.file-max=1844674407370955161

2. fix validate_sysctl_key by adding 
# check the length of the string
if [[ ${#current_value} -lt ${#value} ]]; then
   ...
fi 

Inspired by: https://stackoverflow.com/a/40805454

Testing 1:
test "1844674407370955161" -lt "10" || echo "less"  # less
less

Testing #2:
LANG=C test "18446744073709551615" -lt "10" || echo "less"
bash: test: 18446744073709551615: integer expression expected

**Comment by javsalgar** [comment]
Hi,

Thanks for letting us know. I think it makes sense to add an extra test to check the number length. I will add it to our backlog, but you can create a PR if you wish :)

**Comment by andresbono** [comment]
Hi @yanmorinokamca, thanks for letting us know about this issue.

Do you know if elasticsearch is supported in x86-64 machines?

Note that the container doesn't change the values for `vm.max_map_count` and `fs.file-max`, it just checks the minimum required values:

https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html
https://www.elastic.co/guide/en/elasticsearch/reference/current/file-descriptors.html

**Comment by yanmorinokamca** [comment]
Hi @andresbono

I don't know about  elasticsearch support of theses machines, but they provide a .deb as long as you have Java installed.

Note that the docker container of bitnami-docker-elasticsearch use an amd64 architecture (like my computer, I was just writing the last part of the command uname -a). 
https://github.com/bitnami/bitnami-docker-elasticsearch/blob/master/6/debian-9/Dockerfile

Also, installing and running elasticsearch (as a deb package without container) works with that big value.

**Comment by andresbono** [comment]
Hi @yanmorinokamca, did you already modify the checks to suit your needs?

**Comment by yanmorinokamca** [comment]
Yes, I did on a custom docker build to remove that bug. At the same time,
I've also updated the libelasticsearch.sh directly to add custom
configuration (http cors) to elasticsearch.yml since using a custom file
like -custom.yml no longer works in the last release, well I think. At
least, that's the only way I found to make it work with lando.

**Comment by andresbono** [comment]
Hi @yanmorinokamca, great!!

Are the changes that you have applied public? it would be great if we can apply some of your changes to keep improving our solution.

**Comment by yanmorinokamca** [comment]
Patch Gists:
https://gist.github.com/yanmorinokamca/1772e50a22b66ce2adac6aeb1f6d0c64
- using USER 1000 instead of 1001
- using if [[ ${#current_value} -le ${#value} ]]; then
- using set http.cors

**Comment by andresbono** [comment]
Nice! We'll check which changes make sense to apply in the container.

Thanks!
