### ISSUE TITLE
Use Open Distro for Elasticsearch

### ISSUE THREAD

**Issue by javieryanez** [bitnami/bitnami-docker-elasticsearch#58]
The Amazon, and others, initiative. It is the best alternative to Elasticsearch OSS.

Web site: [https://opendistro.github.io/for-elasticsearch/](https://opendistro.github.io/for-elasticsearch/)
Annoucement: [https://aws.amazon.com/es/blogs/opensource/keeping-open-source-open-open-distro-for-elasticsearch/](https://aws.amazon.com/es/blogs/opensource/keeping-open-source-open-open-distro-for-elasticsearch/)

**Comment by juan131** [comment]
Hi @javieryanez 

Thanks for sharing this information. Our Docker Images are Apache 2.0 licensed and we continuously evaluate the licenses of the components included in them.

We'd like to hear more opinions for the rest of the community to understand what steps to move forward in the future.

We had recently other discussions about the new licenses affecting some of the components used on certain applications such as ElasticSearch or MongoDB (e.g. https://github.com/bitnami/bitnami-docker-mongodb/issues/129).
