### ISSUE TITLE
Install x-pack plugin

### ISSUE THREAD

**Issue by StiviiK** [bitnami/bitnami-docker-elasticsearch#59]
Hi,

I am trying to install the x-pack plugin into my elasticsearch cluster. I deploy elasticsearch with the bitnami helm chart into my k8s cluster. Without plugins everything works fine, but when i add the plugins section to the values.yaml the container keeps crashing at the configuration step.
`INFO  ==> Configuration Elasticsearch cluster settings...`, this is the last message in the console before the container crashes.

I tried these forms of the values.yaml plugins section:
```
plugins:
  - https://artifacts.elastic.co/downloads/packs/x-pack/x-pack-6.2.4.zip
```
```
plugins:
  - x-pack
```
```
plugins: x-pack
```
```
plugins: "x-pack"
```

But none seems working. How can i install the x-pack plugin into the elasticsearch cluster?

For reference my values.yaml:
https://pastebin.com/T0PcKmCK

**Comment by miguelaeh** [comment]
Hi @StiviiK ,
I have reproduce your issue. Executing the command inside of the container The error is the following:
<img width="623" alt="Screen Shot 2019-04-12 at 6 06 50 PM" src="https://user-images.githubusercontent.com/36923089/56051126-fa04e300-5d4d-11e9-8189-f0bce224c0f7.png">

It seems like x-pack is not available with the open source version but I am not familiar with x-pack. Do you know if x-pack is available for the oss version of elasticsearch?

**Comment by StiviiK** [comment]
`> Do you know if x-pack is available for the oss version of elasticsearch?`
I'am not sure, but i fixed my issue by using the official [elastic.co helm](https://github.com/elastic/helm-charts/tree/master/elasticsearch) chart.

**Comment by miguelaeh** [comment]
That is because this image do not use the oss version. We compile the oss version to build our image and it seems that x-pack is not available for that.
Thanks for your report.

**Comment by samaiyayashraj** [comment]
Hi, I'm having the same issue. Want to enable xpack. 
Is there any workaround, still using bitnami/elasticsearch image & bitnami helm chart.

**Comment by javsalgar** [comment]
Hi,

I am afraid that it is not possible as it is directly disabled in the OSS distribution

```
I have no name!@499f626c2fe7:/$ elasticsearch-plugin install x-pack
-> Installing x-pack
-> Failed installing x-pack
ERROR: X-Pack is not available with the oss distribution; to use X-Pack features use the default distribution
```

You may need to create a custom image, where you download the default Elasticsearch distribution, install it in `/opt/bitnami/` and see if our scripts work with this distribution. I am afraid that, at the moment, it is not something we can guarantee.

**Comment by samaiyayashraj** [comment]
Hi, @javsalgar thanks for the reply. 
Here **https://hub.docker.com/_/elasticsearch** is this the oss distribution or default distribution.

**Comment by miguelaeh** [comment]
Hi @samaiyayashraj ,
that is not the ES distribution but their docker image. You should get the ES distribution from their (download page)[https://www.elastic.co/elasticsearch/?ultron=B-Stack-Trials-EMEA-S-Exact&gambit=Elasticsearch-DownloadTerms&blade=adwords-s&hulk=cpc&Device=c&thor=download%20elasticsearch&gclid=CjwKCAiAouD_BRBIEiwALhJH6DZ1top31j5XRfgNIssn1QH4b6quiuhjmqbUFLxIGBJcaMkV-BsWDhoCJSgQAvD_BwE]:

**Comment by samaiyayashraj** [comment]
Hi @miguelaeh , My bad. 
What I wanted to ask is, what is the difference between the oss distribution & default distribution. 
&
Where can I find the oss distribution docker image & default distribution docker image of elasticsearch.

**Comment by miguelaeh** [comment]
Hi @samaiyayashraj ,
The OSS is the open-source distribution. That's the one we package and you can use it without any elasticsearch license. Nevertheless, it has not all the functionality of ES. To use certain features you will need the default distribution and the proper license. This is what happens with the x-pack plugin, it is not available in the OSS distribution.

>Where can I find the OSS distribution docker image & default distribution docker image of elasticsearch.

About this, for the OSS you can use this docker-image (the one at this repo). We don't have an image for the default one.
I can see (this)[https://hub.docker.com/_/elasticsearch] at docker hub but I am not familiar with it. You will need to ask the elastic search team about that image.
