### ISSUE TITLE
Invalid kernel settings. Elasticsearch requires at least: vm.max_map_count = 262144

### ISSUE THREAD

**Issue by yoburtu** [bitnami/bitnami-docker-elasticsearch#61]
**Description**

I am deploying elastic search image in Openshift platform.
**Steps to reproduce the issue:**

1. `$ oc import-image --confirm=true bitnami/elasticsearch:7.0.1`
2. Deploy image.
3. ... And error.

**Describe the results you received:**

Don't deploy image and appears this error in log:
```
Invalid kernel settings. Elasticsearch requires at least: vm.max_map_count = 262144
```
**Describe the results you expected:**

Image deployed.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:
```
OpenShift Master: v3.11.98 
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by miguelaeh** [comment]
Hi @yoburtu ,
The problem here is that Elasticsearch need the kernel parameter `vm.max_map_count = 262144` to be set. Normally, this could be performed by using an init container, but Openshift do not allow to execute containers as root, so it will fail. 
Not sure about if this is possible but, the only option that you have is to connect into the host and change manually the kernel parameter. It is a limitation of Elasticsearch.

**Comment by anoopl** [comment]
I have same error on Kubernetes GKE. How can be this fixed?

**Comment by alemorcuq** [comment]
Hi, @anoopl.

How are you deploying this? As @miguelaeh said, Elasticsearch needs the kernel parameter `vm.max_map_count = 262144`, so you will need to set that.

Regards,
Alejandro

**Comment by achilleas-michos** [comment]
Hi, 
Is there a solution to this? I've tried the following that didn't work:

- Make my own image derived from bitnami where I replace the sysctl.conf
- Using an init container

**Comment by miguelaeh** [comment]
Hi @achilleas-michos ,
Could you provide the init container you used?

**Comment by miguelaeh** [comment]
Hi @achilleas-michos ,
Using kubernetes the container shares the kernel with the physical node of the cluster, so changing the parameter in an initContainer should change the parameter on the node too.

**Comment by odwrotnie** [comment]
I have the same issue :(

**Comment by miguelaeh** [comment]
Hi @odwrotnie ,
Thanks for sharing!! Yes, that is the process to address it, it is a requirement of elasticsearch itself, so the parameter has to be modified in the kernel.

**Comment by mastrobirraio** [comment]
> I have the same issue :(
> 
> ```
> docker run --name elasticsearch bitnami/elasticsearch:latest
> Unable to find image 'bitnami/elasticsearch:latest' locally
> latest: Pulling from bitnami/elasticsearch
> Digest: sha256:1c9b948468e698587fe55658bd276cec1bebbaef1ad885a814afbdf74991f89b
> Status: Downloaded newer image for bitnami/elasticsearch:latest
>  10:02:49.50 
>  10:02:49.50 Welcome to the Bitnami elasticsearch container
>  10:02:49.50 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-elasticsearch
>  10:02:49.50 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-elasticsearch/issues
>  10:02:49.50 Send us your feedback at containers@bitnami.com
>  10:02:49.50 
>  10:02:49.50 INFO  ==> ** Starting Elasticsearch setup **
>  10:02:49.51 ERROR ==> Invalid kernel settings. Elasticsearch requires at least: vm.max_map_count = 262144
> ```
> 
> And solution - you have to set it by:
> 
> ```
> sysctl -w vm.max_map_count=262144
> ```

Works for me

**Comment by arn-ob** [comment]
> I have the same issue :(
> 
> ```
> docker run --name elasticsearch bitnami/elasticsearch:latest
> Unable to find image 'bitnami/elasticsearch:latest' locally
> latest: Pulling from bitnami/elasticsearch
> Digest: sha256:1c9b948468e698587fe55658bd276cec1bebbaef1ad885a814afbdf74991f89b
> Status: Downloaded newer image for bitnami/elasticsearch:latest
>  10:02:49.50 
>  10:02:49.50 Welcome to the Bitnami elasticsearch container
>  10:02:49.50 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-elasticsearch
>  10:02:49.50 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-elasticsearch/issues
>  10:02:49.50 Send us your feedback at containers@bitnami.com
>  10:02:49.50 
>  10:02:49.50 INFO  ==> ** Starting Elasticsearch setup **
>  10:02:49.51 ERROR ==> Invalid kernel settings. Elasticsearch requires at least: vm.max_map_count = 262144
> ```
> 
> And solution - you have to set it by:
> 
> ```
> sysctl -w vm.max_map_count=262144
> ```

Its worked
