### ISSUE TITLE
Why Container getting Exited immediately after docker run or start? 

### ISSUE THREAD

**Issue by gauravaec1** [bitnami/bitnami-docker-elasticsearch#68]
**Description**

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by alemorcuq** [comment]
Hi, @gauravaec1.

We need more information in order to reproduce and identify the issue. Please, fill the template in the issue description.

Regards,
Alejandro

**Comment by gauravaec1** [comment]
Step 1: docker pull gsaxam/elasticsearch-kibana-searchguard-6.2.4
Step 2: docker run gsaxam/elasticsearch-kibana-searchguard-6.2.4
Check for container status : docker ps -a
O/P: 
CONTAINER ID        IMAGE                                                 COMMAND                  CREATED             STATUS                      PORTS               NAMES
d4631d974924        gsaxam/elasticsearch-kibana-searchguard-6.2.4         "/app-entrypoint.sh …"   22 seconds ago      Exited (0) 21 seconds ago 

Expected O/P should be running container, so that i can exec it and use this container.

**docker info**
Containers: 6
 Running: 3
 Paused: 0
 Stopped: 3
Images: 22
Server Version: 18.09.7
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version:
runc version: N/A
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-1094-aws
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.67GiB
Name: ip-172-31-22-210
ID: 6YTN:QR64:D4VT:P437:3ZUJ:CX3Z:CVK3:2AZW:7655:FY5I:YDHD:523N
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

**Comment by alemorcuq** [comment]
Hi, @gauravaec1.

I see you are using this image: `gsaxam/elasticsearch-kibana-searchguard-6.2.4`. Where did you get it from? This is not an official Bitnami image, it's an image someone made based on the Bitnami one. The creators of the image probably introduced some changes in the image that may be causing the issue. Please, contact them to learn more about your issue.

Regards,
Alejandro
