### ISSUE TITLE
no xpack......pitiful

### ISSUE THREAD

**Issue by junneyang** [bitnami/bitnami-docker-elasticsearch#70]

**Comment by carrodher** [comment]
Hi, I am sorry but xpack is not an [OSI approved](https://opensource.org/licenses) open-source software and Bitnami only provides software with OSI approved licenses.

You can modify the Dockerfile and associated files to add this plugin, but we can't provide it by default in the image. Thank you.

**Comment by humblewolf** [comment]
@carrodher Can you please explain the current state of helm-chart/image on X-Pack in 2021, From elasticsearch helm chart docs:

`Also, from now on, the Helm Chart will include the X-Pack plugin installed by default.`

(https://github.com/bitnami/charts/tree/master/bitnami/elasticsearch#to-1500)

If x-pack is available in chart, why its parameters are not in configuration list ? (https://github.com/bitnami/charts/tree/master/bitnami/elasticsearch#parameters)

Is this something related https://github.com/bitnami/charts/pull/6010 ?

**Comment by carrodher** [comment]
x-pack is now bundled by default in the ES container image (https://github.com/bitnami/bitnami-docker-elasticsearch#7120-debian-10-r0), there are some open PRs adding different features to take advantage of this plugin to improve the security and performance of the Helm Chart, for example, https://github.com/bitnami/charts/pull/6486.
It is still work in progress, but something the team is working on
