### ISSUE TITLE
Disable elasticsearch_validate_kernel for coordination node

### ISSUE THREAD

**Issue by sventschui** [bitnami/bitnami-docker-elasticsearch#71]
**Description**

Can we disable `elasticsearch_validate_kernel` for a coordinating node or disable it using a flag? I think it is not really subject to the `max_map_count` restriction or is it?

Happy to raise a PR if you agree on disabling it for coordinating nodes or by a flag

**Steps to reproduce the issue:**

1. Try to run a coordinating only node with a `max_map_count` of `65530`

**Describe the results you received:**

The container fails with an error message

**Describe the results you expected:**

The container starts

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by dani8art** [comment]
Hi @sventschui thank you for your suggestion, let's evaluate it. Could you share with us your run configuration (env vars, volumes, network, links, etc)? could we investigate a bit more about the relationship between `elasticsearch_validate_kernel` and `max_map_count`?

**Comment by sventschui** [comment]
I unfortunately can't share any run configurations as it is not quite simple to reproduce our environment.

We run an elastic cluster across 2 datacenters on VirtualMachines (where we adjust kernel settings according to elastic recommendations). In the same Datacenter there is an OpenShift instance where we do not have control over kernel settings. We want to run a coordinator only node on OpenShift since failover from one DC to the other one is much faster for a docker container/openshift pod than for the VirtualMachines. At least one node must be able to fail over to the other DC as we otherwise loose the quorum when one DC fails completely.

Not sure what you mean about investigating the relationship between `elasticsearch_validate_kernel` and `max_map_count`. I just saw that the said function checks for the recommended kernel settings for elasticsearch and I am pretty sure that a coordinator only node is not really subject to these recommendations as it doesn't store any indexes. I support the validation of the kernel settings to give a user a red flag on systems that are not recommended to run elastic on but in the case of a coordinator only node I think this doesn't make any sense.

I'd suggest to add an env var to weaken the kernel settings checks. I.e. `ELASTICSEARCH_SUPPRESS_MAX_MAP_COUNT_ERROR=yes` resulting in a warning instead of an error.

**Comment by dani8art** [comment]
Ok I understand now better, so let's see your proposal as PR and we can have a further discussion, what do you think?

> Happy to raise a PR if you agree on disabling it for coordinating nodes or by a flag

I would go for the 'flag' option.

**Comment by sventschui** [comment]
I found a workaround by modifying the init scripts using `sed` in my docker command, not pretty but does the job for now. I might not PR a better solution as I currently do not have a lot of time for OSS
