### ISSUE TITLE
could not find java in bundled jdk at /opt/bitnami/elasticsearch/jdk/bin/java

### ISSUE THREAD

**Issue by HemanthGulecha** [bitnami/bitnami-docker-elasticsearch#77]
**Description**

I am upgrading Elastic Search and I have created a chart for the Bitnami ES and I have also added a DockerFile similar to this https://github.com/bitnami/bitnami-docker-elasticsearch/blob/6.8.9-debian-10-r5/7/debian-10/Dockerfile. 
In addition I am also using the elasticsearch-plugin command to install plugin using the readonlyyest.zip file. Specific commands are as listed below.

```
# Install ReadonlyREST plugin
COPY readonlyrest-1.19.5_es7.7.0.zip /opt/bitnami/elasticsearch/
COPY config/readonlyrest.yml  /opt/bitnami/elasticsearch/config/readonlyrest.yml
RUN elasticsearch-plugin install --batch file:////opt/bitnami/elasticsearch/readonlyrest-1.19.5_es7.7.0.zip
```

**Describe the results you received:**

I get the following error when I am trying to build the image 
`could not find java in bundled jdk at /opt/bitnami/elasticsearch/jdk/bin/java`

**Describe the results you expected:**

The same thing when we initially had for v6.7 it worked fine. Help would be appreciated. Thanks in advance

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by rafariossaa** [comment]
Hi @HemanthGulecha ,
  That is not the path for jdk, java is at `/opt/bitnami/java/bin`.
 Could you check your PATH environment var ?

**Comment by Gallardo994** [comment]
Confirming, cannot use elasticsearch-keystore because of this.

Current workaround is to add default env JAVA_HOME=/opt/bitnami/java

**Comment by rafariossaa** [comment]
Hi @Gallardo994,
  Do you mind opening a new issue to check and track your use case ?
  
Thanks forehand.

**Comment by Gallardo994** [comment]
New issue: https://github.com/bitnami/bitnami-docker-elasticsearch/issues/81

**Comment by rafariossaa** [comment]
Hi,
 Thanks you.
