### ISSUE TITLE
Single-node cluster's master node should have the ingest role enabled

### ISSUE THREAD

**Issue by chikamichi** [bitnami/bitnami-docker-elasticsearch#79]
**Description**

A _single-node_ cluster does not have its master node configured with the ingest role enabled, resulting in error when attempting to use ingest pipelines. This is not par with the [default configuration in Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html).

**Steps to reproduce the issue:**

1. Start a container based on bitnami/elasticsearch and with an ingest plugin, such as ingest-attachment
2. Try to index documents

**Describe the results you received:**

An error occurs:

> there are no ingest nodes in this cluster, unable to forward request to an ingest node

**Describe the results you expected:**

Indexing should proceed with the ingest pipeline.

**Additional information you deem important (e.g. issue happens only occasionally):**

None.

**Version**

Not relevant (not a Docker problem).

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Not relevant (not an environment problem).

**Comment by chikamichi** [comment]
The piece of code responsible for enabling flags is [`elasticsearch_configure_node_type`](https://github.com/bitnami/bitnami-docker-elasticsearch/blob/3a143ef610d93b71265ddeb4ed6b3969fb52c6b2/7/debian-10/rootfs/opt/bitnami/scripts/libelasticsearch.sh#L330-L354). It currently follows a logic revolving aronud the concept of dedicated node vs general-purpose node, which does not fit well with a single-node cluster.

Not sure if this issue is actually worth fixing at the library level. My current workaround is to provide custom configuration (see #78) and that could be it. Or, one may consider following the Principle of Least Surprise makes more sense and single-node clusters should be supported out of the box :thinking:

**Comment by javsalgar** [comment]
Hi,

Thank you very much for the feedback. I believe that we should support a single node configuration or at least document it. I will open a task for evaluation. When we have more news, I will update this ticket.

**Comment by ashnehete** [comment]
Upvote for having support or resources related to single node clusters. My current use case involves largely ephemeral testing environments for which a multi-node cluster could just be a waste of resources. I'm open to contribute as well.

**Comment by darraghenright** [comment]
@ashnehete Did you ever manage to work out how to do this? I'm looking for a way to configure single-node clusters for largely ephemeral use — sounds like a similar use case to yours.

**Comment by fmulero** [comment]
This requests has more than a year and there is no plan to implement it in short term.

We are also moving to [a new repository](https://github.com/bitnami/containers) in order to be aligned with the approach followed in [bitnami/charts](https://github.com/bitnami/charts). More information [here](https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html). If you are still interested on this feature, please open a new issue in [bitnami/containers](https://github.com/bitnami/containers) repository
