### ISSUE TITLE
elasticsearch-keystore doesn't work due to error: "could not find java in JAVA_HOME at /opt/bitnami/elasticsearch/jdk/bin/java"

### ISSUE THREAD

**Issue by Gallardo994** [bitnami/bitnami-docker-elasticsearch#81]
**Description**

Bitnami Elasticsearch Docker containers cannot execute **elasticsearch-keystore** commands, resulting into:
**could not find java in JAVA_HOME at /opt/bitnami/elasticsearch/jdk/bin/java**

**Steps to reproduce the issue:**

1. Start vanilla bitnami/elasticsearch:7.8.1 container
2. Docker exec into container: **elasticsearch-keystore add asdf**
3. Get the error in stdout: **could not find java in JAVA_HOME at /opt/bitnami/elasticsearch/jdk/bin/java**

**Describe the results you received:**

Error shows up: **could not find java in JAVA_HOME at /opt/bitnami/elasticsearch/jdk/bin/java**

**Describe the results you expected:**

Prompt for keystore value

**Additional information you deem important (e.g. issue happens only occasionally):**

The issue is fixed by setting ENV variable:
JAVA_HOME=/opt/bitnami/java

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:07 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 56
  Running: 32
  Paused: 0
  Stopped: 24
 Images: 50
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-112-generic
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 31.31GiB
 Name: ovh-backup0
 ID: WGWG:Y4SZ:PVE2:24KX:5YUN:FV2L:WY2Y:B2RA:WGWF:ZJXT:AFIE:YOYY
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Running Docker on vanilla Ubuntu 18.04 (OVH-hosted). Reproducable on any machine

**Comment by Gallardo994** [comment]
Pull request: https://github.com/bitnami/bitnami-docker-elasticsearch/pull/82

**Comment by juan131** [comment]
Thanks so much for reporting this issue!! Checking your PR

**Comment by juan131** [comment]
Solved at https://github.com/bitnami/bitnami-docker-elasticsearch/pull/82
