### ISSUE TITLE
Container crash on  windows 10

### ISSUE THREAD

**Issue by maorz555** [bitnami/bitnami-docker-elasticsearch#87]
Docker version 19.03.13, build 4484c46d9d

INFO ==> ** Starting Elasticsearch setup **
ERROR ==> Invalid kernel settings. Elasticsearch requires at least: vm.max_map_count = 262144

any help ?

**Comment by dani8art** [comment]
Hi @maorz555 it seems to be very similar to https://github.com/bitnami/bitnami-docker-elasticsearch/issues/61, https://github.com/bitnami/bitnami-docker-elasticsearch/issues/43 or https://github.com/bitnami/bitnami-docker-magento/issues/151.

Could you take a look at those issues? they may help you.

Thanks!
