### ISSUE TITLE
Install Elasticsearch in IBM Cloud

### ISSUE THREAD

**Issue by datta-TG** [bitnami/bitnami-docker-elasticsearch#88]
# Install Elasticsearch in IBM Cloud

This documentation will guide you on how to install Elasticsearch on the IBM Cloud using the Kubernetes Service. Simple and effective.

## Pre-requisites

You must have an account created in IBM Cloud. The account needs to be either be *Pay-As-You-Go* or *Subscription*. Click [here](https://cloud.ibm.com/docs/account?topic=account-accounts "here") to read more.
If you have a Lite account, you can upgrade it. Click [here](https://cloud.ibm.com/docs/account?topic=account-account-getting-started#account-gs-upgrade "here") to learn how to upgrade.

## Step 1: Provision Kubernetes Cluster

* Click on the search section at the top of the main page, type Kubernetes, and then choose Kubernetes Service.

![Kubernetes1](https://user-images.githubusercontent.com/70336951/105564934-54d4b800-5cf2-11eb-82b7-ab1dae6fab74.PNG)

* In the new window, select between the free and standard type under "Pricing plan". Once selected, click on create.

![KubernetesPaid1](https://user-images.githubusercontent.com/70336951/105564957-72a21d00-5cf2-11eb-9757-82e7c2cc33bd.PNG)

We'll choose the Standard Plan for this documentation as the Free Plan may fall short of resources when deploying your pods. We highly recommend using a Standard Plan with the hardware that suits you the best. If you're selecting the Standard Plan, please make sure you select the adequate requirements,

* Select your Kubernetes Version to be the latest available or the required one by your application. In this example, we have set it to be '1.18.13'.
* Select Infrastructure as 'Classic'.
* Leave Resource Group to 'Default'.
* Select Geography to the one that suits you better or that fits your infrastructure.
* Select Availability to be 'Single Zone' or 'Multi Zone' depending on your needs.
* Select a Worker Zone that suits you better or that fits your infrastructure.

![KubernetesPaid2](https://user-images.githubusercontent.com/70336951/105564967-82b9fc80-5cf2-11eb-9098-43a721b539ac.PNG)

* Select the number of workers in Worker Pool.
* Give your Worker Pool a name.
* Leave the Encrypt Local Disk option 'On'
* Choose 'Both private and public endpoints' on Master Service Endpoint

![KubernetesPaid4](https://user-images.githubusercontent.com/70336951/105564980-91a0af00-5cf2-11eb-8dc5-5843b5469a50.PNG)

* Give your cluster a name in 'cluster-name'
* Provide the tags to your cluster and click on Create.

![KubernetesPaid5](https://user-images.githubusercontent.com/70336951/105564994-9feecb00-5cf2-11eb-9968-d0b73a759bda.PNG)

Wait a few minutes while your cluster is deployed.

![KubernetesPaid3](https://user-images.githubusercontent.com/70336951/105565004-abda8d00-5cf2-11eb-997b-f2b6c6e58e11.PNG)

The following checkmark and the word 'normal' will appear once the Kubernetes Cluster is deployed. You can check it under your cluster section which is located in your *Resources List*.

![KubernetesPaid6](https://user-images.githubusercontent.com/70336951/105565015-b563f500-5cf2-11eb-8ec1-854fc070cadc.PNG)

## Step 2:  Deploy IBM Cloud Block Storage plug-in

* Click on the search section at the top of the main page, select IBM Cloud Block Storage, and click on it.

![StoragePaid1](https://user-images.githubusercontent.com/70336951/105565026-c4e33e00-5cf2-11eb-9781-35ad0fd37000.PNG)

* A new window opens, select the cluster and enter the name you want for this workspace, in this case, it will be called _storage-example_, accept the terms, click *Install* and wait a few minutes.

![StoragePaid2](https://user-images.githubusercontent.com/70336951/105565034-cf9dd300-5cf2-11eb-8eaf-71c51f804a05.PNG)

## Step 3: Install Elasticsearch

* Click on the search section at the top of the main page, type Elasticsearch, and click on it.

![elastic1](https://user-images.githubusercontent.com/70336951/105565045-dfb5b280-5cf2-11eb-99ef-ad8729c0984b.png)

* A new window opens, select the cluster, and then select the workspace you want Elasticsearch to be installed. You can also write a new workspace. In this case, we will use the previously created _storage-example_ workspace. Type a workspace name under 'Configure your workspace', accept the terms and click on *Install*. You can modify the different installation parameters at the bottom. We will leave them by default as shown below, but you can read more about setting up the parameters [here](https://cloud.ibm.com/catalog/content/elasticsearch "here").

![elastic3](https://user-images.githubusercontent.com/70336951/105565056-f0662880-5cf2-11eb-97d3-36aea26ee26e.png)

## Step 4: Verify Installation

* Go to *Resources List* in the Left Navigation Menu and click on *Kubernetes*.

![test11](https://user-images.githubusercontent.com/70336951/105565070-feb44480-5cf2-11eb-8d30-9f5a82c4e3e7.png)

* Click the *Actions* button and select *Web terminal*.

![test2](https://user-images.githubusercontent.com/70336951/105565621-b64a5600-5cf5-11eb-9c36-9a6a33db75ba.PNG)

* A window opens to install the web terminal, click on install and wait a few minutes. The window will pop up at the buttom If the web terminal is already installed.

![test3](https://user-images.githubusercontent.com/70336951/105565110-20adc700-5cf3-11eb-9078-41e1b9f4bcdd.png)

![test7](https://user-images.githubusercontent.com/70336951/105565111-23a8b780-5cf3-11eb-88ee-5ed6811a5986.PNG)

* Once you have installed the terminal, open it, select web terminal, and type the following command. It will show you the workspaces of your cluster. You can see *storage-example* is active.

`$ kubectl get ns`

![testelastic2](https://user-images.githubusercontent.com/70336951/105565124-302d1000-5cf3-11eb-8cb2-8db7f8a16df5.png)

* You can then obtain more data about the service and it's pods. In this case we want to know the pods of the *storage-example* service.

`$ kubectl get pod -n NAMESERVICE`

![testelastic1](https://user-images.githubusercontent.com/70336951/105565133-3b803b80-5cf3-11eb-8028-9b972bcecd76.png)

`$ kubectl get service -n NAME SERVICE`

![testelastic4](https://user-images.githubusercontent.com/70336951/105565148-4a66ee00-5cf3-11eb-98a5-86e6443a5abf.png)

* Select the pod within your service using bash so you can start using Elasticsearch from the terminal.

`$ kubectl exec --stdin --tty PODNAME -n NAMESPACE -- /bin/bash`

![testelastic6](https://user-images.githubusercontent.com/70336951/105565159-5baffa80-5cf3-11eb-9f3b-72998b6f194c.png)

* You can send the following command and Elasticsearch will return its version in the respond, along with other info. That way you know that Elasticsearch is now active.

`$ curl -XGET 'localhost:9200'`

![testelastic5](https://user-images.githubusercontent.com/70336951/105565167-69658000-5cf3-11eb-932f-809743881958.png)

You have finished the installation, enjoy your Elasticsearch installation!

**Comment by carrodher** [comment]
Thanks for the info. As it seems that there is no issue we should take action and everything works properly, I am going to mark this issue as "Closed" so it can be used by other users looking for information as if it were documentation
