### ISSUE TITLE
Add possibility to override jvm.options

### ISSUE THREAD

**Issue by korektur** [bitnami/bitnami-docker-elasticsearch#90]
Currently it's possible to override elasticsearch configuration via supplying my_elasticsearch.yml file with custom configuration. Hovewer it's not possible to override jvm.options, which sometimes should be changed for performance reasons.

One of the examples is to change default gc. I believe currently it's using CMS all the time, which probably makes sense on smaller heaps. But on larger heaps G1 performs much better, however in default configuration it's just commented out. There are many more additonal jvm properties that user might need to configure, such as:  jmx, jvm heapdump path, etc.

Proposal is to allow user specify my_jvm.options and replace jvm.options with it on startup.

**Comment by marcosbc** [comment]
Hi @korektur, have you tried mounting your custom `jvm.options` file? That's how we'd recommend configuring it for now. If it doesn't work, please share any errors so we can resolve it.

Also, is this request related to the Bitnami chart for Elasticsearch? Or were you just trying to override it for the container?

**Comment by korektur** [comment]
@marcosbc  I was trying to override it for the container.
The problem is that one of your scripts replaces Xmx options in jvm.options with values from the proeprties. Which is ok, but that means it requires write permissions for that file during ES startup. The problem is that ine recent versions of kubernetes when you mount file from config map it's only read only and it's not possible to write into it. (https://stackoverflow.com/questions/52046908/are-kubernetes-configmaps-writable).

I understand that there are workarounds on how to mount a file from configmap as writable, but I think that correct approach is to support this through image config, for example like with elasticsearch.yml.

**Comment by marcosbc** [comment]
Hi @korektur, I understand now, thanks for the details.

We're planning on applying the following changes to `libelasticsearch.sh` so that you can mount the `jvm.options` files without issues:

```diff
@@ -6,6 +6,7 @@
 # shellcheck disable=SC1091

 # Load Generic Libraries
+. /opt/bitnami/scripts/libfs.sh
 . /opt/bitnami/scripts/libfile.sh
 . /opt/bitnami/scripts/liblog.sh
 . /opt/bitnami/scripts/libnet.sh
@@ -172,12 +173,12 @@ elasticsearch_validate_kernel() {
     }

     debug "Validating Kernel settings..."
-    if [[ $(yq r "$ELASTICSEARCH_CONF_FILE" index.store.type) || $(yq r "$ELASTICSEARCH_CONF_FILE" '[index.store.type]') ]]; then
+    if [[ $(yq r "$ELASTICSEARCH_CONF_FILE" index.store.type) ]]; then
         debug "Custom index.store.type found in the config file. Skipping kernel validation..."
     else
         validate_sysctl_key "fs.file-max" 65536
     fi
-    if [[ $(yq r "$ELASTICSEARCH_CONF_FILE" node.store.allow_mmap) || $(yq r "$ELASTICSEARCH_CONF_FILE" '[node.store.allow_mmap]') ]]; then
+    if [[ $(yq r "$ELASTICSEARCH_CONF_FILE" node.store.allow_mmap) ]]; then
         debug "Custom node.store.allow_mmap found in the config file. Skipping kernel validation..."
     else
         validate_sysctl_key "vm.max_map_count" 262144
@@ -444,6 +445,20 @@ elasticsearch_initialize() {
         am_i_root && chown -R "$ELASTICSEARCH_DAEMON_USER:$ELASTICSEARCH_DAEMON_GROUP" "$dir"
     done

+    if is_file_writable "${ELASTICSEARCH_CONF_DIR}/jvm.options"; then
+        if is_boolean_yes "$ELASTICSEARCH_DISABLE_JVM_HEAP_DUMP"; then
+            info "Disabling JVM heap dumps..."
+            replace_in_file "${ELASTICSEARCH_CONF_DIR}/jvm.options" "-XX:[+]HeapDumpOnOutOfMemoryError" "# -XX:+HeapDumpOnOutOfMemoryError"
+        fi
+        if is_boolean_yes "$ELASTICSEARCH_DISABLE_GC_LOGS"; then
+            info "Disabling JVM GC logs..."
+            replace_in_file "${ELASTICSEARCH_CONF_DIR}/jvm.options" "8:-Xloggc:logs[/]gc.log" "# 8:-Xloggc:logs/gc.log"
+        fi
+        elasticsearch_set_heap_size
+    else
+        warn "The '${ELASTICSEARCH_CONF_DIR}/jvm.options' file is not writable. Configurations based on environment variables will not be applied for this file"
+    fi
+
     if [[ -f "$ELASTICSEARCH_CONF_FILE" ]]; then
         info "Custom configuration file detected, using it..."
     else
@@ -454,19 +469,10 @@ elasticsearch_initialize() {
         elasticsearch_conf_set transport.tcp.port "$ELASTICSEARCH_NODE_PORT_NUMBER"
         is_boolean_yes "$ELASTICSEARCH_ACTION_DESTRUCTIVE_REQUIRES_NAME" && elasticsearch_conf_set action.destructive_requires_name "true"
         is_boolean_yes "$ELASTICSEARCH_LOCK_ALL_MEMORY" && elasticsearch_conf_set bootstrap.memory_lock "true"
-        if is_boolean_yes "$ELASTICSEARCH_DISABLE_JVM_HEAP_DUMP"; then
-            info "Disabling JVM heap dumps..."
-            replace_in_file "${ELASTICSEARCH_CONF_DIR}"/jvm.options "-XX:[+]HeapDumpOnOutOfMemoryError" "# -XX:+HeapDumpOnOutOfMemoryError"
-        fi
-        if is_boolean_yes "$ELASTICSEARCH_DISABLE_GC_LOGS"; then
-            info "Disabling JVM GC logs..."
-            replace_in_file "${ELASTICSEARCH_CONF_DIR}"/jvm.options "8:-Xloggc:logs[/]gc.log" "# 8:-Xloggc:logs/gc.log"
-        fi
         elasticsearch_cluster_configuration
         elasticsearch_configure_node_type
         elasticsearch_custom_configuration
     fi
-    elasticsearch_set_heap_size
 }

 ########################
```

We will let you know once those changes are published.

**Comment by marcosbc** [comment]
Hi @korektur, just wanted to let you know that we released `bitnami/elasticsearch:
6.8.14-debian-10-r27` and `bitnami/elasticsearch:7.10.2-debian-10-r57`, which include a fix for the issues you were finding.

Hope it works for you!

**Comment by korektur** [comment]
Thanks!
