### ISSUE TITLE
Error: Deployment.apps "elasticsearch-coordinating-only" is invalid: spec.template.spec.initContainers[0].securityContext.privileged: Forbidden: disallowed by cluster policy

### ISSUE THREAD

**Issue by patsevanton** [bitnami/bitnami-docker-elasticsearch#94]
Hello! I try install elasticsearch by helm from bitnami

```
helm repo add bitnami https://charts.bitnami.com/bitnami
helm install elasticsearch bitnami/elasticsearch
```

Get error
```
Error: Deployment.apps "elasticsearch-coordinating-only" is invalid: spec.template.spec.initContainers[0].securityContext.privileged: Forbidden: disallowed by cluster policy
```

**Version**

- Output of `docker version`:

```
i use microk8s
```

- Output of `docker info`:

```
i use microk8s
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
microk8s - 1.18
helm 3.6.2

**Comment by alvneiayu** [comment]
hi @patsevanton 

Could you try to add --allow-privileged into /var/snap/microk8s/current/args/kube-apiserver and do a restart with microk8s.stop; microk8s.start?

Thanks a lot

Álvaro

**Comment by patsevanton** [comment]
@alvneiayu It works. Thanks!
