### ISSUE TITLE
Elastic 8 support

### ISSUE THREAD

**Issue by kvokka** [bitnami/bitnami-docker-elasticsearch#96]
### Name and Version

bitnami-docker-elasticsearch:7

### What is the problem this feature will solve?

Elastic 8.1 was [released](https://www.elastic.co/guide/en/elasticsearch/reference/current/release-highlights.html), but the image stuck with 7.x.x version.

Since the core components are updated under closed repos, there is no way but to ask the support team to make such a big move.

### What is the feature you are proposing to solve the problem?

Upgrade elastic version to 8.x

**Comment by rafariossaa** [comment]
Hi,
  Thanks for requesting this.
  Elasticsearch 8 is currently under our radar. I will be released soon but I can not provide an ETA.
